### ISSUE TITLE
Search filter should be sentence case

### ISSUE THREAD

**Issue by hackajesse** [CityOfBoston/search.boston.gov#4]
On the page showing results of a search query, the left side filter says "Filter by Type". It should say "Filter by type" with a lowercase T in Type.

![search-filter-capitalization](https://cloud.githubusercontent.com/assets/3886936/21614305/ed3736a8-d1a6-11e6-85a5-67a760ff63e8.PNG)

**Comment by matthewcrist** [comment]
Done on search.boston.gov.
